// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    // apiKey: 'AIzaSyAu-irZlQwTaZ24eiOVHph5o6RxgnTvLjk',
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    // appId: '1:1084566191832:android:b0a10d6591cad287b061ad',
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID']!,
    // messagingSenderId: '1084566191832',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
    // projectId: 'messanger-ui',
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    // storageBucket: 'messanger-ui.appspot.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    // apiKey: 'AIzaSyAzrv_yVxXbA1bug01NuhrT3MSSnXUOZGQ',
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    // appId: '1:1084566191832:ios:e856f0db733e3c37b061ad',
    appId: dotenv.env['FIREBASE_IOS_APP_ID']!,
    // messagingSenderId: '1084566191832',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
    // projectId: 'messanger-ui',
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    // storageBucket: 'messanger-ui.appspot.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
    // iosBundleId: 'com.example.messangerUi',
    iosBundleId: dotenv.env['FIREBASE_IOS_BUNDLE_ID']!,
  );

}