import 'package:messanger_ui/model/usermodel.dart';

List<UserModel> users = [
  UserModel(
    uid: 'xxxCfdGHty',
    username: 'user1',
    pfpURL: 'assets/images/Pfp0.jpeg',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'YtrA6HjKlZ',
    username: 'sunny_day',
    pfpURL: 'assets/images/Pfp0.jpeg',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'OpLkJmNbVc',
    username: 'coolcat',
    pfpURL: 'assets/images/Pfp0.jpeg',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'BnmPqRsTuv',
    username: 'moonwalker',
    pfpURL: 'assets/images/Pfp0.jpeg',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'ZxCvBnLmPo',
    username: 'star_gazer',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'AsDfGhJkLq',
    username: 'tech_guru',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'WeRtYuiOpL',
    username: 'wanderlust',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'AzQwScXdeR',
    username: 'bookworm',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'YioPlQWeRt',
    username: 'gamer123',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'VbNjKyUiOl',
    username: 'foodie',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'MnBvCxLkJh',
    username: 'nature_lover',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'ZxCvBNMlKj',
    username: 'music_fan',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'PlMnQweRty',
    username: 'art_enthusiast',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'AsDfGhJkLm',
    username: 'travel_bug',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'WvXyZnPqLk',
    username: 'fitness_freak',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'QsZaWdfXcv',
    username: 'code_master',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'PlMoNbVcXz',
    username: 'movie_buff',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'KjLwErTyUi',
    username: 'garden_guru',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'QazWsXedCv',
    username: 'fashionista',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
  UserModel(
    uid: 'YuiOlPqWeRt',
    username: 'sports_fanatic',
    pfpURL: 'assets/images/Pfp.png',
    videoPath: 'assets/videos/story/Calculatorappvideo.mp4',
    played: false,
  ),
];
